Feature add header buttons
VikOrlovskiy/Filmoteka-team-project pull request #9
Opened 2022-01-12 19:28 UTC by SerhBondarenko

1) FT-12 Сверстать хедер для страницы "My Library" (мобилка, планшет, десктоп)
2) По нажатию на кнопку My Library появляються кнопки Watched  и Queue через Js

2022-01-12 19:36 UTC, VikOrlovskiy commented on src/js/Refs.js
> +    buttonHome: document.querySelector('.current-link'),
Странный класс для селектора

2022-01-12 19:37 UTC, VikOrlovskiy commented on src/js/Refs.js
> +    onHeaderContainer:document.querySelector('.header__container'),
Почему везде он ?

2022-01-12 19:40 UTC, VikOrlovskiy commented on src/js/renderUserLibrary.js
> +};
Слишком много что накидали  , должен один контейнер скрится а другой появится и поменяется фон хедера , все

2022-01-12 19:41 UTC, VikOrlovskiy commented on src/templates/fetchMovieTemplate.hbs
> +  <article>
Где идёт фильма ?

2022-01-12 19:41 UTC, VikOrlovskiy commented on src/templates/fetchMovieTemplate.hbs
> +  <article>
Ид

2022-01-12 19:42 UTC, VikOrlovskiy requested changes
Неплохо но нужно поправить

2022-01-12 20:26 UTC, SerhBondarenko commented on src/js/Refs.js
> +    onHeaderContainer:document.querySelector('.header__container'),
исправил

2022-01-12 20:26 UTC, SerhBondarenko commented on src/js/renderUserLibrary.js
> +};
исправил. чуть уменьшил остальное все надо.

2022-01-13 07:14 UTC, VikOrlovskiy approved these changes

2022-01-13 07:14 UTC, merged